spike/views/default.py
from flask import Blueprint, redirect, Response, current_app, send_from_directory, request, url_for
from werkzeug.contrib.atom import AtomFeed
from datetime import datetime

from spike.model.naxsi_rules import NaxsiRules

default = Blueprint('default', __name__)


@default.route("/")
def index():
    return redirect("/rules")


@default.route("/download")
def download():
    return send_from_directory(directory=current_app.root_path, filename='rules.db', as_attachment=True)


@default.route("/robots.txt")
def robots():
    return Response('User-agent: *\n Disallow: /', mimetype='text/plain')


@default.route('/rules.atom')
def atom():
    feed = AtomFeed(title='Recent rules', feed_url=request.url, url=request.url_root, author='Spike',
                    icon=url_for('static', filename='favicon.ico'))
    _rules = NaxsiRules.query.order_by(NaxsiRules.sid.desc()).limit(15).all()
    if _rules:
        for rule in _rules:
            feed.add(rule.msg, str(rule), updated=datetime.fromtimestamp(rule.timestamp), id=rule.sid)
    return feed.get_response()

spike/views/doxi_admin.py
from __future__ import with_statement
from flask import Blueprint, redirect, Response, current_app, send_from_directory, request, url_for, flash, render_template
from werkzeug.contrib.atom import AtomFeed
from functools import wraps
from datetime import datetime
from hashlib import sha512
from shutil import copytree, copy, copyfile 

from simplejson import dumps as jdumps
from simplejson import loads as jloads
from simplejson import dump as jdump
from simplejson import load as jload


import os, time 

from spike.model.naxsi_rules import NaxsiRules as nx_rules
from spike.model.doxi_admin import DoxiAdmin as dx_admin
from spike.model.doxi_admin import DoxiAdminRuleSets as dx_rulesets
from spike.model.doxi_admin import DoxiAdminSettings as dx_settings
from spike.model.doxi_rules import NaxsiRules as dx_rules

from spike.model import get_db_session 

from spike.views import time_stamp

doxi_admin = Blueprint('doxi_admin', __name__)

#
# helperfuncs
#

# need to check if export-info is to be displayed
@doxi_admin.context_processor
def check_export_needed():
  doxi_temp = current_app.config["DOXI_TEMP"]
  needs_export_file = "%s/needs_export.yes" % doxi_temp
  export_display = {}
  export_display["needs_export"] = "no"
  export_display["reload_pending"] = "no"
  if os.path.isfile(needs_export_file):
    print "NEEDS EXPORT"
    export_display["needs_export"]  = "yes"
  reload_pending = "%s/reload.pending" % doxi_temp
  if os.path.isfile(reload_pending):
    print "RELOAD PENDING"
    export_display["reload_pending"]  = "yes"
  return dict(export_display=export_display)

# check if locked due to reload pending
def check_if_reload_pending(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
      doxi_temp = current_app.config["DOXI_TEMP"]
      reload_pending = "%s/reload.pending" % doxi_temp
      if os.path.isfile(reload_pending):
        print "RELOAD PENDING"
        return redirect(url_for("doxi_admin.reload_pending"))      
      return f(*args, **kwargs)
    return decorated_function


#
# </helperfuncs
#




@doxi_admin.route("/")
def index():

  # check if first run
  doxi_temp = current_app.config["DOXI_TEMP"]
  if not os.path.isdir(doxi_temp):
    print "INIT doxi_admin"
    doxi_init()
  db_session = get_db_session("spike/doxi_rules.db")
  db_session_adm = get_db_session("spike/doxi_admin.db")
  all_rules = db_session.query(dx_rules).order_by(dx_rules.sid.desc()).all()
  rules_dict = {}
  for r in all_rules:
    rules_string = r.fullstr()
    rules_dict[r.sid] = { "msg": r.msg, "detect": r.detection, "ruleset": r.ruleset, "active": r.active, "new": 1, "mz": r.mz, "rmks": r.rmks, "fullstr": rules_string }
    deact = db_session_adm.query(dx_admin).filter(dx_admin.sid == r.sid).order_by(dx_admin.id.desc()).first()
    if deact:
      rules_dict[r.sid]["active"] = deact.active 
      rules_dict[r.sid]["new"] = 0 
      
    #~ if not _rules:
      #~ flash("No rules found, please create one", "success")
      #~ return redirect(url_for("rules.new"))
  return render_template("doxi_admin/index.html", rules=rules_dict)



@doxi_admin.route("/reload_pending")
def reload_pending():
  
  return render_template("doxi_admin/reload_pending.html")

@doxi_admin.route("/reload_status/<path:reload_status_id>")
def reload_status(reload_status_id):

  doxi_temp = current_app.config["DOXI_TEMP"]
  local_rules = "%s/local-rules" % doxi_temp
  restarts = "%s/restarts" % doxi_temp  
  reload_pending =  "%s/reload.pending" % doxi_temp
  

  status_file = "%s/%s/status.json" % (restarts, reload_status_id)
  if not os.path.isfile(status_file):
    flash("cannot find status_id: %s" % reload_status_id, "danger")
    reload_msg = {}
  else:
    reload_msg = jloads("".join(open(status_file, "r").readlines()))
    
  return render_template("doxi_admin/reload_status.html", reload_msg = reload_msg )


@doxi_admin.route("/reload_execute")
def reload_execute():
  
  reload_data = update_rules()
  
  print reload_data
  
  reload_status_id = reload_data["reload_id"]
  
  return redirect(url_for("doxi_admin.reload_status", reload_status_id  = reload_status_id))     
  


@doxi_admin.route("/config_test")
def config_test():
  
  flash("config_test not yet available", "info")
  return redirect(url_for("doxi_admin.index"))     


@doxi_admin.route("/export")
@check_if_reload_pending
def export():

  ets = time_stamp()

  doxi_temp = current_app.config["DOXI_TEMP"]
  local_rules = "%s/local-rules" % doxi_temp
  needs_export = "%s/needs_export.yes" % doxi_temp
  db_session = get_db_session("spike/doxi_rules.db")
  db_session_adm = get_db_session("spike/doxi_admin.db")
  all_rules = db_session_adm.query(dx_admin.sid).distinct().order_by(dx_admin.sid.desc())
  rules_dict = {}
  rules_count = 0
  for r in all_rules:
    rules_count += 1
    rules_data = db_session.query(dx_rules).filter(dx_rules.sid == r.sid).order_by(dx_rules.id.desc()).first()
    rules_adm = db_session_adm.query(dx_admin).filter(dx_admin.sid == r.sid).order_by(dx_admin.id.desc()).first()
    rules_prefix = ""
    rules_string = rules_data.fullstr()
    if rules_adm.active == 0:
      rules_prefix = "# DEACT because $REASONS \n"
      rf = []
      for l in rules_string.split("\n"):
        l = l.strip()
        if l[0] != "#":
          rf.append("# %s" % l)
        else:
          rf.append(l)
      rules_string = "\n".join(rf)
    rules_fullstring = "%s%s" % (rules_prefix,  rules_string)
    if rules_data.ruleset in rules_dict:
      rules_dict[rules_data.ruleset].append(rules_fullstring)
    else:
      rules_dict[rules_data.ruleset] = [rules_fullstring]
      
  
  for ruleset in rules_dict:
    f = open("%s/%s" % (local_rules, ruleset), "w")
    for e in  rules_dict[ruleset]:
      f.write("%s \n\n\n" % e)
    f.close()
  
  id_desc = "%s.%s" % (current_app.config["SECRET_KEY"], time.time())
  
  print "ID_DESC: %s " % id_desc 
  reload_id = sha512(id_desc).hexdigest()[0:8]
  
  reload_pending = "%s/reload.pending" % doxi_temp
  f = open(reload_pending, "w")
  f.write("id: %s \nexport done: %s \nwaiting for reload\n" % (reload_id, ets))
  f.close()  
  
  export_log_entry =  "%s - export done, id: %s, %s rules, %s rulesets, reload pending" % (reload_id, ets, rules_count, len(rules_dict))

  export_log(export_log_entry)
  os.unlink(needs_export)
  flash("%s" % export_log_entry, "success")
  return redirect(url_for("doxi_admin.index"))

def export_log(in_put):
  doxi_temp = current_app.config["DOXI_TEMP"]
  export_log = "%s/export.log" % doxi_temp
  f = open(export_log, "a")
  f.write("%s \n" % in_put)
  f.close()
  
  



@doxi_admin.route("/manage_rules", methods=["POST"])
@check_if_reload_pending
def manage_rules():



  itemset = {}
  
  itemset["action"] = {}
  itemset["ruleset"] = {}
  # thank you you stupid js-developerZ
  # a value SHOULD be 1 || 0 and not 1 || NIL
  itemset["action_ids"] = []
  

  
  ts = int(time.time())

  
  for item  in request.form:
    itemz = request.form.getlist(item)
    #~ print itemz[0]
    item_target = item.split(".")[0]
    #~ if item_target not in itemset:
      #~ continue 
    action_id = int(item.split(".")[1])

    if action_id == 42000467:
      print "precheck"
      print action_id
      print itemz[0]

    if item_target == "action":
      if itemz[0].lower() == "on":
        itemset[item_target][action_id] = 1        
    else:
      itemset[item_target][action_id] = itemz[0].lower()
    itemset["action_ids"].append(action_id)
  
  for aid in itemset["action_ids"]:
    if not aid in itemset["action"]:
      itemset["action"][aid] = 0
    
        
  
  # select * from doxi_admin where sid =  '42000467'

    # check if first run
  db_session = get_db_session("spike/doxi_rules.db")
  db_session_adm = get_db_session("spike/doxi_admin.db")
  os.system("ls -la spike/doxi_rules.db")
  action_items = itemset["action"] 
  ruleset_dict = itemset["ruleset"] 
  needs_export = 0
  for r in action_items:
    if r == 42000467:
      print r
      print action_items[r]
      print ruleset_dict[r]
    change_src = "default"
    execute = "yes"
    is_known = db_session_adm.query(dx_admin).filter(dx_admin.sid == r).order_by(dx_admin.id.desc()).first()
    if is_known:
      if int(is_known.active) == int(action_items[r]):
        execute = "no"
        
      else:
        change_src = "custom"
    if execute == "yes":
      needs_export = 1
      dx = dx_admin(sid=r, ruleset = ruleset_dict[r], active = action_items[r], change_src =  change_src, timestamp = ts)
      db_session_adm.add(dx)
      #~ print execute
  db_session_adm.commit()
  flash("rulesets updated", "success")
  if needs_export == 1:
    flash("export needed", "danger")
    export_pending_msg()
  return redirect(url_for("doxi_admin.index"))


@doxi_admin.route("/rulesets")
@check_if_reload_pending
def rulesets():

  db_session = get_db_session("spike/doxi_rules.db")
  db_session_adm = get_db_session("spike/doxi_admin.db")
  ts = int(time.time())


  rulesdb_rulesets =   db_session.query(dx_rules.ruleset).distinct()
  
  doxi_rulesets =  db_session_adm.query(dx_rulesets.ruleset).distinct()
  
  for r in rulesdb_rulesets:
    r_known = db_session_adm.query(dx_rulesets).filter(dx_rulesets.ruleset == r.ruleset).first()
    if not r_known:
      new_r = dx_rulesets(ruleset = r.ruleset, active=1, timestamp= ts)
      db_session_adm.add(new_r)
      db_session_adm.commit()
      flash("new ruleset added to doxi_admin <strong>%s</strong> "  % r.ruleset, "success")


  doxi_rulesets =  db_session_adm.query(dx_rulesets).distinct()
  
  ruleset_dict = {}
  for r in doxi_rulesets:
    r_vals = db_session_adm.query(dx_rulesets).filter(dx_rulesets.ruleset == r.ruleset).order_by(dx_rulesets.id.desc()).first()
    ruleset_dict[r.ruleset] = r_vals 
  

  return render_template("doxi_admin/rulesets.html", rulesets=ruleset_dict)

@doxi_admin.route("/manage_rulesets", methods=["POST"])
@check_if_reload_pending
def manage_rulesets():



  itemset = {}
  
  itemset["action"] = {}

spike/views/sandbox.py
try:
    from urlparse import parse_qs
except ImportError:  # python3
    from urllib.parse import parse_qs

from flask import Blueprint, render_template, request, redirect, flash, url_for

from nxapi import nxlog

from spike.model.naxsi_rules import NaxsiRules
from spike.model.naxsi_whitelist import NaxsiWhitelist

sandbox = Blueprint('sandbox', __name__)


@sandbox.route("/", methods=["GET"])
def index():
    return render_template("misc/sandbox.html")


@sandbox.route("/explain_rule/", methods=["GET", "POST"])
def explain_rule():
    errors = warnings = list()
    rule_get = request.args.get('rule', '')
    rule_post = request.form.get("rule", '')
    if rule_get.isdigit():  # explain a rule by id
        _rule = NaxsiRules.query.filter(NaxsiRules.sid == rule_get).first()
        if _rule is None:
            flash('Not rule with id %s' % rule_get)
            return redirect(url_for("sandbox.index"))
    elif rule_get is not '':
        flash('Please provide a numeric id')
        return redirect(url_for("sandbox.index"))
    elif not rule_post:
        flash('Please provide a rule')
        return redirect(url_for("sandbox.index"))
    else:
        _rule = NaxsiRules()
        errors, warnings, rdict = _rule.parse_rule(rule_post)
        _rule = NaxsiRules()
        _rule.from_dict(rdict)
        _rule.errors = errors
        _rule.warnings = warnings

        if _rule.errors:
            flash('You rule is wrong', 'error')
            return render_template("misc/sandbox.html")

    if 'visualise_rule' in request.form:
        if _rule.detection.startswith('rx:'):
            return redirect('https://regexper.com/#' + _rule.detection[3:])
        else:
            flash('The rule is not a regexp, so you can not visualize it.', category='error')

    if errors:
        for error in errors:
            flash(error, category='error')
    if warnings:
        for warnings in warnings:
            flash(warnings, category='warning')

    return render_template("misc/sandbox.html", rule_explaination=_rule.explain(), rule=_rule)


@sandbox.route("/explain_whitelist/", methods=["GET", "POST"])
def explain_whitelist():
    whitelist_get = request.args.get('whitelist', '')
    whitelist_post = request.form.get('whitelist', '')
    if whitelist_get.isdigit():  # explain a whitelist by id
        _wl = NaxsiWhitelist.query.filter(NaxsiWhitelist.id == whitelist_get).first()
        if _wl is None:
            flash('Not rule with id %s' % whitelist_get)
            return redirect(url_for("sandbox.index"))
    elif whitelist_get is not '':
        flash('Please provide a numeric id')
        return redirect(url_for("sandbox.index"))
    elif not whitelist_post:
        flash('Please provide a whitelist')
        return redirect(url_for("sandbox.index"))
    else:
        _wl = NaxsiWhitelist()
        errors, warnings, rdict = _wl.parse(whitelist_post)
        _wl = NaxsiWhitelist()
        _wl.from_dict(rdict)
        _wl.errors = errors
        _wl.warnings = warnings

    if _wl.errors:
        for error in _wl.errors:
            flash(error, category='error')
            return render_template("misc/sandbox.html", whitelist=_wl)
    if _wl.warnings:
        for warnings in _wl.warnings:
            flash(warnings, category='warning')

    return render_template("misc/sandbox.html", whitelist_explaination=_wl.explain(), whitelist=_wl)


@sandbox.route('/explain_nxlog/', methods=["POST"])
def explain_nxlog():
    _nxlog = request.form.get("nxlog", '')
    if not _nxlog:
        return redirect(url_for("sandbox.index"))

    errors, nxdic = nxlog.parse_nxlog(_nxlog)
    if errors:
        flash(''.join(errors))
        return redirect(url_for("sandbox.index"))

    return render_template("misc/sandbox.html", nxlog_explaination=nxlog.explain_nxlog(nxdic), nxlog=_nxlog)

spike/views/site_admin.py
from __future__ import with_statement
from flask import Blueprint, redirect, Response, current_app, send_from_directory, request, url_for, flash, render_template
from werkzeug.contrib.atom import AtomFeed
from functools import wraps
from datetime import datetime
from hashlib import sha512
from shutil import copytree, copy, copyfile 

from simplejson import dumps as jdumps
from simplejson import loads as jloads
from simplejson import dump as jdump
from simplejson import load as jload


import os, time 

#~ from spike.model.naxsi_rules import NaxsiRules as nx_rules
#~ from spike.model._admin import DoxiAdmin as dx_admin
#~ from spike.model.site_admin import DoxiAdminRuleSets as dx_rulesets
#~ from spike.model.site_admin import DoxiAdminSettings as dx_settings
#~ from spike.model.doxi_rules import NaxsiRules as dx_rules

from spike.model import get_db_session 

from spike.views import time_stamp

site_admin = Blueprint('site_admin', __name__)

#
# helperfuncs
#


@site_admin.route("/")
def index():

  # check if first run
  doxi_temp = current_app.config["DOXI_TEMP"]
  if not os.path.isdir(doxi_temp):
    print "INIT site_admin"
    doxi_init()
  db_session = get_db_session("spike/doxi_rules.db")
  db_session_adm = get_db_session("spike/site_admin.db")
  all_rules = db_session.query(dx_rules).order_by(dx_rules.sid.desc()).all()
  rules_dict = {}
  for r in all_rules:
    rules_string = r.fullstr()
    rules_dict[r.sid] = { "msg": r.msg, "detect": r.detection, "ruleset": r.ruleset, "active": r.active, "new": 1, "mz": r.mz, "rmks": r.rmks, "fullstr": rules_string }
    deact = db_session_adm.query(dx_admin).filter(dx_admin.sid == r.sid).order_by(dx_admin.id.desc()).first()
    if deact:
      rules_dict[r.sid]["active"] = deact.active 
      rules_dict[r.sid]["new"] = 0 
      
    #~ if not _rules:
      #~ flash("No rules found, please create one", "success")
      #~ return redirect(url_for("rules.new"))
  return render_template("site_admin/index.html", rules=rules_dict)

spike/templates/misc/doxi_admin.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils%}




{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='javascript/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='javascript/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='javascript/bootstrap-toggle.min.js') }}"></script>
{% endblock %}


{% block styles %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="{{ url_for('static', filename='css/fonts.css') }}" rel="stylesheet" media="screen"/>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" media="screen"/>
    <link href="{{ url_for('static', filename='css/appstyle.css') }}" rel="stylesheet" media="screen"/>
    <link href="{{ url_for('static', filename='css/bootstrap-toggle.min.css') }}" rel="stylesheet" media="screen"/>

    <link href="{{ url_for('default.atom') }}" type="application/atom+xml" rel="alternate" />
{% endblock %}


{% block navbar %}
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="/doxi_admin">
                Spoxi <img src="{{ url_for('static', filename='spike.png') }}" alt="Spike logo">
            </a>
        </div>

        <div class="collapse navbar-collapse navbar-collapse-top">
            <ul class="nav navbar-nav navbar-left">
                <li class="dropdown">
                    <a href="/doxi_admin" class="dropdown-toggle" data-toggle="dropdown">Doxi_Admin<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('site_admin.index') }}">Manage Sites</a></li>
                        <li><hr></li>
                        <li><a href="{{ url_for('doxi_admin.index') }}">Manage Rules</a></li>
                        <li><a href="{{ url_for('doxi_admin.rulesets') }}">Manage Rulesets</a></li>
                        <li><a href="{{ url_for('doxi_admin.updates_admin') }}">Execute Updates</a></li>
                        <li><hr></li>
                        <li><a href="{{ url_for('doxi_admin.settings') }}">Export</a></li>
                        <li><a href="{{ url_for('doxi_admin.settings') }}">Settings</a></li>
                        <li><a href="{{ url_for('doxi_admin.config_test') }}">Config_Test</a></li>

                    </ul>

                </li>

            </ul>

            <div class="navbar-right">




                <form class="navbar-form" action="{{ url_for('doxi_admin.search') }}" method="get" role="search">
                    <div class="form-group">
                  {% if export_display["reload_pending"] == "yes" %}
                    
                    <a href="{{ url_for('doxi_admin.reload_execute') }}" class="btn btn-warning headbtn">Reload Pending</a> &nbsp;&nbsp; &nbsp; &nbsp;

                  {% elif export_display["needs_export"] == "yes" %}
                  
                    <a href="{{ url_for('doxi_admin.export') }}" class="btn btn-danger headbtn">Activation/Export needed</a> &nbsp;&nbsp; &nbsp; &nbsp;

                  
                  {% endif  %}
                            <input type="text" class="form-control" name="s" size="20" value="{{ lsearch }}" placeholder="Keyword or rule id">
                        <input type="submit" class="btn btn-primary" value="Search">
                    </div>
                </form>
            </div>
        </div>
    </nav>

{% endblock %}


{% block content %}
    <div class="main-content">
        <div class="row"><br><br><br></div>  <!-- This is ugly as fuck, fix it with css and love
          yeah, UI-DEVS to the front!!!!!!!!! (mex) -->

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {{ utils.flashed_messages(dismissible=True) }}

                {% block main %}
                {% endblock %}

            </div>
        </div>



{% endblock content %}


        <div class="row footer">
            <div class="container" align="center">
                <hr>
                Copyright 2011-2015,2017 lazy.dog</a>,
                2016 <a href="https://nbs-system.com" target="_blank">NBS-System</a>
                <br/>
                Version: <a href="https://github.com/nbs-system/spike>">{{ version }}</a>
                - Logo: <a href="http://www.iconsdb.com/moth-green-icons/barking-dog-icon.html">IconDB</a>
                <hr>
            </div>
        </div>
    </div>

spike/templates/misc/sandbox.html
{% extends "misc/application.html" %}

{% block main %}

    <h2>Rule explainer</h2>
    <form action="{{ url_for('sandbox.explain_rule') }}" method="POST">
        <div class="row top-buffer1">
            <div class="col-md-1">
                <textarea name="rule" cols="90" rows="5" placeholder="Your shiny rule here">{{ rule }}</textarea>
            </div>
        </div>

        {% if rule_explaination %}
        <div class="row top-buffer">
            <div class="col-md-6">
                <blockquote>
                    {{ rule_explaination | safe }}
                </blockquote>
            </div>
        </div>
        {% endif %}

        <div class="row top-buffer">
            <div class="col-md-6">
                <div class="btn-toolbar" role="toolbar">
                    <button type="submit" class="btn btn-info" name="explain_rule">Explain</button>
                    <button type="submit" class="btn btn-info" name="visualise_rule">Visualise the regexp</button>
                    <a href="https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules" target='_blank' class="btn btn-default">Examples</a>
                </div>
            </div>
        </div>
    </form>

    <hr>

    <h2>NXLog explainer</h2>
    <form action="{{ url_for('sandbox.explain_nxlog') }}" method="POST">
        <div class="row top-buffer1">
            <div class="col-md-1">
                <textarea name="nxlog" cols="90" rows="5" placeholder="Your shiny nxlog here">{{ nxlog }}</textarea>
            </div>
        </div>

        {% if nxlog_explaination %}
        <div class="row top-buffer">
            <div class="col-md-6">
                <blockquote>
                    {{ nxlog_explaination | safe }}
                </blockquote>
            </div>
        </div>
        {% endif %}

        <div class="row top-buffer">
            <div class="col-md-6">
                <div class="btn-toolbar" role="toolbar">
                    <button type="submit" class="btn btn-info" name="log_explain">Explain</button>
                    <a href="https://github.com/nbs-system/naxsi/wiki/naxsilogs" target='_blank' class="btn btn-default">Examples</a>
                </div>
            </div>
        </div>
    </form>

    <hr>

    <h2>Whitelist explainer</h2>
    <form action="{{ url_for('sandbox.explain_whitelist') }}" method="POST">
        <div class="row top-buffer1">
            <div class="col-md-1">
                <textarea name="whitelist" cols="90" rows="5" placeholder="Your shiny whitelist here">{{ whitelist }}</textarea>
            </div>
        </div>

        {% if whitelist_explaination %}
        <div class="row top-buffer">
            <div class="col-md-6">
                <blockquote>
                    {{ whitelist_explaination | safe }}
                </blockquote>
            </div>
        </div>
        {% endif %}

        <div class="row top-buffer">
            <div class="col-md-6">
                <div class="btn-toolbar" role="toolbar">
                    <button type="submit" class="btn btn-info" name="whitelist_explain">Explain</button>
                    <a href="https://github.com/nbs-system/naxsi/wiki/whitelists" target='_blank' class="btn btn-default">Examples</a>
                </div>
            </div>
        </div>
    </form>


{% endblock %}

spike/templates/misc/whitelist_generator.html
{% extends "misc/application.html" %}

{% block main %}

    <h2>Whitelist generator</h2>
    <form action="{{ url_for('whitelists.generate') }}" method="POST">
        <div class="row top-buffer1">
            <div class="col-md-1">
                <textarea name="nxlogs" cols="120" rows="12" placeholder="Paste your nxlogs here">{{ nxlogs }}</textarea>
            </div>
        </div>

        {% if whitelist %}
        <div class="row top-buffer">
            <div class="col-md-6">
                <blockquote>
                    {{ whitelist | safe }}
                </blockquote>
            </div>
        </div>
        {% endif %}

        <div class="row top-buffer">
            <div class="col-md-6">
                <div class="btn-toolbar" role="toolbar">
                    <button type="submit" class="btn btn-info" name="submit">Generate</button>
                </div>
            </div>
        </div>
    </form>


{% endblock %}