spike/views/sandbox.py
try:
    from urlparse import parse_qs
except ImportError:  # python3
    from urllib.parse import parse_qs

from flask import Blueprint, render_template, request, redirect, flash, url_for

from nxapi import nxlog

from spike.model.naxsi_rules import NaxsiRules
from spike.model.naxsi_whitelist import NaxsiWhitelist

sandbox = Blueprint('sandbox', __name__)


@sandbox.route("/", methods=["GET"])
def index():
    return render_template("misc/sandbox.html")


@sandbox.route("/explain_rule/", methods=["GET", "POST"])
def explain_rule():
    errors = warnings = list()
    rule_get = request.args.get('rule', '')
    rule_post = request.form.get("rule", '')
    if rule_get.isdigit():  # explain a rule by id
        _rule = NaxsiRules.query.filter(NaxsiRules.sid == rule_get).first()
        if _rule is None:
            flash('Not rule with id %s' % rule_get)
            return redirect(url_for("sandbox.index"))
    elif rule_get is not '':
        flash('Please provide a numeric id')
        return redirect(url_for("sandbox.index"))
    elif not rule_post:
        flash('Please provide a rule')
        return redirect(url_for("sandbox.index"))
    else:
        _rule = NaxsiRules()
        errors, warnings, rdict = _rule.parse_rule(rule_post)
        _rule = NaxsiRules()
        _rule.from_dict(rdict)
        _rule.errors = errors
        _rule.warnings = warnings

        if _rule.errors:
            flash('You rule is wrong', 'error')
            return render_template("misc/sandbox.html")

    if 'visualise_rule' in request.form:
        if _rule.detection.startswith('rx:'):
            return redirect('https://regexper.com/#' + _rule.detection[3:])
        else:
            flash('The rule is not a regexp, so you can not visualize it.', category='error')

    if errors:
        for error in errors:
            flash(error, category='error')
    if warnings:
        for warnings in warnings:
            flash(warnings, category='warning')

    return render_template("misc/sandbox.html", rule_explaination=_rule.explain(), rule=_rule)


@sandbox.route("/explain_whitelist/", methods=["GET", "POST"])
def explain_whitelist():
    whitelist_get = request.args.get('whitelist', '')
    whitelist_post = request.form.get('whitelist', '')
    if whitelist_get.isdigit():  # explain a whitelist by id
        _wl = NaxsiWhitelist.query.filter(NaxsiWhitelist.id == whitelist_get).first()
        if _wl is None:
            flash('Not rule with id %s' % whitelist_get)
            return redirect(url_for("sandbox.index"))
    elif whitelist_get is not '':
        flash('Please provide a numeric id')
        return redirect(url_for("sandbox.index"))
    elif not whitelist_post:
        flash('Please provide a whitelist')
        return redirect(url_for("sandbox.index"))
    else:
        _wl = NaxsiWhitelist()
        errors, warnings, rdict = _wl.parse(whitelist_post)
        _wl = NaxsiWhitelist()
        _wl.from_dict(rdict)
        _wl.errors = errors
        _wl.warnings = warnings

    if _wl.errors:
        for error in _wl.errors:
            flash(error, category='error')
            return render_template("misc/sandbox.html", whitelist=_wl)
    if _wl.warnings:
        for warnings in _wl.warnings:
            flash(warnings, category='warning')

    return render_template("misc/sandbox.html", whitelist_explaination=_wl.explain(), whitelist=_wl)


@sandbox.route('/explain_nxlog/', methods=["POST"])
def explain_nxlog():
    _nxlog = request.form.get("nxlog", '')
    if not _nxlog:
        return redirect(url_for("sandbox.index"))

    errors, nxdic = nxlog.parse_nxlog(_nxlog)
    if errors:
        flash(''.join(errors))
        return redirect(url_for("sandbox.index"))

    return render_template("misc/sandbox.html", nxlog_explaination=nxlog.explain_nxlog(nxdic), nxlog=_nxlog)

spike/views/whitelists.py
try:
    from urlparse import parse_qs
except ImportError:  # python3
    from urllib.parse import parse_qs
import logging
from time import time

from flask import Blueprint, render_template, request, redirect, flash, Response, url_for

from spike.model import db
from spike.model.naxsi_whitelist import NaxsiWhitelist
from spike.model.naxsi_whitelistsets import NaxsiWhitelistSets
from spike.model import naxsi_mz

whitelists = Blueprint('whitelists', __name__)


@whitelists.route("/")
def index():
    _wlist = NaxsiWhitelist.query.order_by(NaxsiWhitelist.wl.desc()).all()
    if not _wlist:
        flash("No whitelist found, please create one", "success")
        return redirect(url_for('whitelists.new'))
    return render_template("whitelists/index.html", whitelists=_wlist)


@whitelists.route("/plain/<string:wid>", methods=["GET"])
def plain(wid):
    _wlist = NaxsiWhitelist.query.filter(NaxsiWhitelist.id == wid).first()
    if not _wlist:
        flash("No rules found, please create one", "error")
        return redirect(url_for('whitelists.index'))
    return Response(str(_wlist), mimetype='text/plain')


@whitelists.route("/view/<int:wid>", methods=["GET"])
def view(wid):
    _wlist = NaxsiWhitelist.query.filter(NaxsiWhitelist.id == wid).first()
    if _wlist is None:
        flash("The whitelist %d was not found." % wid, "error")
        return redirect(url_for('whitelists.index'))
    return render_template("whitelists/view.html", whitelist=_wlist)


@whitelists.route("/edit/<string:wid>", methods=["GET"])
def edit(wid):
    return redirect(url_for('whitelists.new'))


@whitelists.route("/del/<string:wid>", methods=["GET"])
def del_sid(wid):
    _wlist = NaxsiWhitelist.query.filter(NaxsiWhitelist.id == wid).first()
    if not _wlist:
        return redirect(url_for('whitelists.index'))

    db.session.delete(_wlist)
    db.session.commit()

    flash("Successfully deleted %s" % wid, "success")
    return redirect(url_for('whitelists.index'))


@whitelists.route("/generate", methods=["GET", "POST"])
def generate():
    if request.method == "GET":
        return render_template("misc/whitelist_generator.html")
    nxlogs = request.form.get('nxlogs', '')

    if not nxlogs:
        flash('Please input nxlogs')
        return render_template("misc/whitelist_generator.html")

    whitelist = set()
    for nxlog in nxlogs.split('\n'):
        nxlog = nxlog.strip()
        if not nxlog:
            continue
        start = nxlog.find("ip=")
        if start < 0:
            flash('{} is an invalid extlog, string "ip=" not found.'.format(nxlog))
            return render_template("misc/whitelist_generator.html", nxlogs=nxlogs)

        end = nxlog.find(", ")
        if end < 0:
            flash('{} is an invalid extlog, string "," not found.'.format(nxlog))
            return render_template("misc/whitelist_generator.html", nxlogs=nxlogs)

        # Flatten the dict, since parse_qs is a bit annoying
        nxdic = parse_qs(nxlog[start:end])
        for key, value in nxdic.items():
            nxdic[key] = value[0]

        cpt = 0
        while "id{}".format(cpt) in nxdic:
            _id = "id{}".format(cpt)
            _var_name = "var_name{}".format(cpt)
            _zone = "zone{}".format(cpt)
            if nxdic[_zone].endswith('|NAME'):
                if "var_name{}".format(cpt) in nxdic:
                    whitelist.add('BasicRule wl:{} "mz:${}_VAR:{}|NAME"'.format(nxdic[_id], nxdic[_zone][:4], nxdic[_var_name]))
                else:
                    whitelist.add('BasicRule wl:{} "mz:{}"'.format(nxdic[_id], nxdic[_zone]))
            elif "var_name{}".format(cpt) in nxdic:
                whitelist.add('BasicRule wl:{} "mz:{}:{}"'.format(nxdic[_id], "$"+nxdic[_zone]+"_VAR", nxdic[_var_name]))
            else:
                whitelist.add('BasicRule wl:{} "mz:{}"'.format(nxdic[_id], nxdic[_zone]))
            cpt += 1
    return render_template("misc/whitelist_generator.html", whitelist='<br>'.join(whitelist) + ';', nxlogs=nxlogs)


@whitelists.route('/new', methods=["GET", "POST"])
def new():
    if request.method == "GET":
        _whitelistesets = NaxsiWhitelistSets.query.all()
        return render_template('whitelists/new.html', matchzones=naxsi_mz, whitelistsets=_whitelistesets)

    logging.debug('Posted new request: %s', request.form)

    mz = request.form.getlist("mz") + request.form.getlist("custom_mz_val")
    wid = request.form.get('wl', '')
    whitelistset = request.form.get("whitelistset", '')

    if not wid:
        flash('Please enter a wl', category='error')
        return render_template('whitelists/new.html')
    elif not whitelistset:
        flash('Please enter a whitelistset', category='error')
        return render_template('whitelists/new.html')

    wlist = NaxsiWhitelist(wl=wid, timestamp=int(time()),
                           whitelistset=whitelistset, mz=mz, active=1,
                           negative=request.form.get("negative", "") == 'checked')
    errors, warnings = wlist.validate()

    if errors:
        flash(",".join(errors), 'error')
        return redirect(url_for('whitelists.new'))
    elif warnings:
        flash(",".join(warnings), 'warning')

    wlist.mz = '|'.join(wlist.mz)
    db.session.add(wlist)
    db.session.commit()

    return render_template('whitelists/index.html')

spike/templates/whitelists/index.html
{% extends "misc/application.html" %}
{% block title %}SPIKE! - WAF Rules Builder{% endblock %}

{% block main %}

    <h2>Naxsi - Whitelists ( {{ whitelists | length }} )</h2>
    <p><strong>{{ selection }}</strong></p>

    <hr>

    {% for whitelist in whitelists %}
        <div class="row top-buffer1">
            <div class="col-md-2">
                <h5><b>{{ whitelist.wid }}</b></h5>
            </div>

            <div class="col-md-1">
                <h5>{{ whitelist.mz }}</h5>
            </div>

            <div class="col-md-3">
                <div class="btn-toolbar" role="toolbar">
                    <a href="{{ url_for('whitelists.edit', wid=whitelist.wid) }}" class="btn btn-info" title="Edit whitelist">Edit</a>
                    <a href="{{ url_for('whitelists.view', wid=whitelist.id) }}" class="btn btn-default" title="View whitelist">View</a>
                    <a href="{{ url_for('sandbox.explain_whitelist', rule=whitelist.wid) }}" class="btn btn-default" title="Explain whitelist">Explain</a>
                    <a href="{{ url_for('whitelists.plain', wid=whitelist.wid ) }}" class="btn btn-default" title="Plain whitelist">Plain</a>
                    <a href="{{ url_for('whitelists.del_sid', wid=whitelist.wid) }}" class="btn btn-danger" title="Del whitelist">Delete</a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock main %}

spike/templates/whitelists/new.html
{% extends "misc/application.html" %}
{% block title %}New whitelist{% endblock %}


{% block main %}

    <h2>New whitelist</h2>

    <form action="{{ url_for('whitelists.new') }}" method="POST">
        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Whitelisted ID</h5>
            </div>

            <div class="col-md-6">
                <input type="text" name="wl" size="60" placeholder="wl:42,41,43" required>
            </div>
        </div>

        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Matchzone</h5>
            </div>

            <div class="col-md-6">
                {% for matchzone in matchzones %}
                    <input title="matchzone" type="checkbox" name="mz" value="{{ matchzone }}"> {{ matchzone }} <br>
                {% endfor %}
                <input title="custom_mz" type="checkbox" name="custom_mz" value="on">
                <input title="custom_mz_val" type="text" name="custom_mz_val" placeholder="Custom MZ">
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Negative</h5>
            </div>

            <div class="col-md-6">
                <input title="negative" type="checkbox" name="negative" value="checked">
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Whitelistset</h5>
            </div>

            <div class="col-md-1">
                    <select title="whitelistset" name="whitelistset">
                        {% for whitelistset in whitelistsets %}
                            <option value="{{ whitelistset.name }}"> {{ whitelistset.name }}
                        {% endfor %}
                    </select>
            </div>

            <div class="col-md-1">
                <a href="{{ url_for('whitelists.index') }}" class="btn btn-info btn-xs">new whitelistset</a>
            </div>
        </div>

    
        <div class="row top-buffer1">
            <div class="col-md-6">
                <button type="submit" class="btn btn-success btn-lg">Save whitelist</button>
            </div>
        </div>
    </form>
{% endblock %}

spike/templates/whitelists/view.html
{% extends "misc/application.html" %}
{% block title %}View {{ whitelist.id }} {% endblock %}


{% block main %}

    <h3>
        <a href="{{ url_for('whitelists.edit', wid=whitelist.id) }}">{{ whitelist.id }}</a>
        <a href="{{ url_for('whitelists.edit', wid=whitelist.id) }}" class="btn btn-lg btn-primary">Edit whitelist</a>
    </h3>

    <pre>
  
{{ whitelist }}

    </pre>


{% endblock %}