spike/views/rules.py
import logging
import re
import string

from time import time
from flask import Blueprint, render_template, request, redirect, flash, Response, url_for
from sqlalchemy.exc import IntegrityError

from spike.model import db
from spike.model.naxsi_rules import NaxsiRules
from spike.model.naxsi_rulesets import NaxsiRuleSets
from spike.model import naxsi_mz, naxsi_score

rules = Blueprint('rules', __name__)


@rules.route("/")
def index():
    _rules = NaxsiRules.query.order_by(NaxsiRules.sid.desc()).all()
    if not _rules:
        flash("No rules found, please create one", "success")
        return redirect(url_for("rules.new"))
    return render_template("rules/index.html", rules=_rules)


@rules.route("/plain/<int:sid>", methods=["GET"])
def plain(sid):
    _rule = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    if not _rule:
        flash("No rules found, please create one", "error")
        return redirect(url_for("rules.new"))
    return Response(_rule.fullstr(), mimetype='text/plain')


@rules.route("/view/<int:sid>", methods=["GET"])
def view(sid):
    _rule = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    if _rule is None:
        flash("no rules found, please create one", "error")
        return redirect(url_for("rules.index"))
    return render_template("rules/view.html", rule=_rule, rtext=_rule)


@rules.route("/search/", methods=["GET"])
def search():
    terms = request.args.get('s', '')

    if len(terms) < 2:
        return redirect(url_for("rules.index"))

    # No fancy injections
    whitelist = set(string.ascii_letters + string.digits + ':-_ ')
    filtered = ''.join(filter(whitelist.__contains__, terms))

    if filtered.isdigit():  # get rule by id
        _rules = db.session.query(NaxsiRules).filter(NaxsiRules.sid == int(filtered))
    else:
        cve = re.search('cve:\d{4}-\d{4,}', filtered, re.IGNORECASE)  # search by CVE

        expression = '%' + filtered + '%'
        _rules = db.session.query(NaxsiRules).filter(
            db.or_(
                NaxsiRules.msg.like(expression),
                NaxsiRules.rmks.like(expression),
                NaxsiRules.detection.like(expression)
            )
        )
        if cve:
            _rules.filter(NaxsiRules.msg.like('%' + cve.group() + '%'))
    _rules = _rules.order_by(NaxsiRules.sid.desc()).all()
    return render_template("rules/index.html", rules=_rules, selection="Search: %s" % filtered, lsearch=terms)


@rules.route("/new", methods=["GET", "POST"])
def new():
    latest_sid = NaxsiRules.query.order_by(NaxsiRules.sid.desc()).first()
    if latest_sid is None:
        sid = 200001
    else:
        sid = latest_sid.sid + 1

    if request.method == "GET":
        _rulesets = NaxsiRuleSets.query.all()
        return render_template("rules/new.html", mz=naxsi_mz, rulesets=_rulesets, score=naxsi_score, latestn=sid)

    # create new rule
    logging.debug('Posted new request: %s', request.form)
    mz = "|".join(filter(len, request.form.getlist("mz") + request.form.getlist("custom_mz_val")))

    score = request.form.get("score", "")
    score += ':'
    score += request.form.get("score_%s" % request.form.get("score", ""), "")

    nrule = NaxsiRules(request.form.get("msg", ""), request.form.get("detection", ""), mz, score, sid,
                       request.form.get("ruleset", ""), request.form.get("rmks", ""), "1",
                       request.form.get("negative", "") == 'checked', int(time()))

    errors, warnings = nrule.validate()

    if errors:
        for error in errors:
            flash(error, category='error')
        return redirect(url_for("rules.new"))
    elif warnings:
        for warning in warnings:
            flash(warning, category='warnings')

    db.session.add(nrule)
    db.session.commit()

    return redirect("/rules/edit/%s" % sid)


@rules.route("/test/<int:sid>", methods=["GET", "POST"])
def test(sid):
    _rule = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    if _rule is None:
        flash("no rules found, please create one", "error")
        return redirect(url_for("rules.index"))
    return render_template("rules/test.html", rule=_rule, rtext=_rule)


@rules.route("/edit/<int:sid>", methods=["GET", "POST"])
def edit(sid):
    rinfo = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    if not rinfo:
        return redirect(url_for("rules.index"))

    _rulesets = NaxsiRuleSets.query.all()
    rruleset = NaxsiRuleSets.query.filter(NaxsiRuleSets.name == rinfo.ruleset).first()
    custom_mz = ""
    mz_check = rinfo.mz
    if re.search(r"^\$[A-Z]+:(.*)\|[A-Z]+", mz_check):
        custom_mz = mz_check
        rinfo.mz = "custom"
    return render_template("rules/edit.html", mz=naxsi_mz, rulesets=_rulesets, score=naxsi_score, rules_info=rinfo,
                           rule_ruleset=rruleset, custom_mz=custom_mz)


@rules.route("/save/<int:sid>", methods=["POST"])
def save(sid):
    mz = "|".join(filter(len, request.form.getlist("mz") + request.form.getlist("custom_mz_val")))
    score = "{}:{}".format(request.form.get("score", ""), request.form.get("score_%s" % request.form.get("score", "")))
    nrule = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    nrule.msg = request.form.get("msg", "")
    nrule.detection = request.form.get("detection", "")
    nrule.mz = mz
    nrule.score = score
    nrule.ruleset = request.form.get("ruleset", "")
    nrule.rmks = request.form.get("rmks", "")
    nrule.active = request.form.get("active", "")
    nrule.negative = request.form.get("negative", "") == 'checked'
    nrule.timestamp = int(time())
    errors, warnings = nrule.validate()

    if errors:
        flash(",".join(errors), 'error')
        return redirect("/rules/edit/%s" % sid)
    elif warnings:
        flash(",".join(warnings), 'warning')

    db.session.add(nrule)
    db.session.commit()

    return redirect("/rules/edit/%s" % sid)


@rules.route("/del/<int:sid>", methods=["GET"])
def del_sid(sid=''):
    nrule = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    if not nrule:
        return redirect(url_for("rules.index"))

    db.session.delete(nrule)
    db.session.commit()

    flash("Successfully deleted %s : %s" % (sid, nrule.msg), "success")
    return redirect(url_for("rules.index"))


@rules.route("/deact/<int:sid>", methods=["GET"])
def deact(sid):
    nrule = NaxsiRules.query.filter(NaxsiRules.sid == sid).first()
    if nrule is None:
        return redirect(url_for("rules.index"))

    fm = 'deactivate' if nrule.active else 'reactivate'
    nrule.active = not nrule.active

    db.session.add(nrule)
    db.session.commit()

    flash("Successfully deactivated %s %sd : %s" % (fm, sid, nrule.msg), "success")
    _rulesets = NaxsiRuleSets.query.all()
    return render_template("rules/edit.html", mz=naxsi_mz, rulesets=_rulesets, score=naxsi_score, rules_info=nrule)


@rules.route("/import", methods=["POST", "GET"])
def import_rules():
    if request.method == "GET":
        return render_template("rules/import.html", rulesets=NaxsiRuleSets.query.all())

    ruleset = request.form.get("ruleset", "")
    upfile = request.files.get('file', '')

    if not ruleset or not upfile:
        flash("Missing rule file and/or ruleset name.", 'error')
        return redirect(url_for("rules.new"))

    raw = upfile.stream.getvalue()

    success_imports = 0
    potential_imports = 0
    for potential_rule in raw.split('\n'):
        potential_rule = potential_rule.strip()
        if not potential_rule or potential_rule.startswith("#"):  # Save ourselves some time by not trying to import comments
            continue
        potential_imports += 1
        _rule = NaxsiRules(ruleset=ruleset, active=1)
        errors, warnings, rule = _rule.parse_rule(potential_rule)

        if errors:
            flash("Fail to parse %s: %s" % (potential_rule, ', '.join(errors)), 'error')
            continue
        else:
            db.session.add(rule)
            try:
                db.session.commit()
                success_imports += 1
            except IntegrityError:
                db.session.rollback()
                flash("Rule %s has not an unique ID" % rule['sid'])
    flash("Imported %d rules out of %d lines in ruleset %s" % (success_imports, potential_imports, ruleset))

    return render_template("rules/import.html", rulesets=NaxsiRuleSets.query.all())

spike/views/rulesets.py
from time import time, localtime, strftime

from flask import current_app, Blueprint, render_template, request, redirect, flash, Response, url_for

from spike.model import db
from spike.model.naxsi_rules import NaxsiRules
from spike.model.naxsi_rulesets import NaxsiRuleSets


rulesets = Blueprint('rulesets', __name__)


@rulesets.route("/")
def index():
    _rulesets = NaxsiRuleSets.query.order_by(NaxsiRuleSets.name).all()
    return render_template("rulesets/index.html", rulesets=_rulesets)


@rulesets.route("/plain/")
@rulesets.route("/plain/<int:rid>")
def plain(rid=0):
    """
    Show the rule `rid` in plain text
    :param int rid: Rule id
    """
    if not rid:
        out = ''.join(map(__get_rules_for_ruleset, NaxsiRuleSets.query.all()))
    else:
        out = __get_rules_for_ruleset(NaxsiRuleSets.query.filter(NaxsiRuleSets.id == rid).first())
    return Response(out, mimetype='text/plain')


@rulesets.route("/view/<int:rid>")
def view(rid):
    ruleset = NaxsiRuleSets.query.filter(NaxsiRuleSets.id == rid).first()
    return render_template("rulesets/view.html", r=ruleset, rout=__get_rules_for_ruleset(ruleset))


@rulesets.route("/new", methods=["POST"])
def new():  # TODO filter parameter
    rname = request.form["rname"].strip().upper()

    if NaxsiRuleSets.query.filter(NaxsiRuleSets.name == rname).first():
        flash("Ruleset %s is already existing" % rname, "error")
        return redirect(url_for("rulesets.index"))

    db.session.add(NaxsiRuleSets(rname, "naxsi-ruleset: %s" % rname, int(time())))
    db.session.commit()

    flash("OK created: %s " % rname, "success")
    return redirect(url_for("rulesets.index"))


@rulesets.route("/del/<int:rname>", methods=["POST"])
def remove(rname):
    _rset = NaxsiRuleSets.query.filter(NaxsiRuleSets.id == rname).first()
    if _rset is None:
        flash("The ruleset %s doesn't exists." % rname, "error")
        return redirect(url_for("rulesets.index"))

    db.session.delete(_rset)
    db.session.commit()

    flash("OK deleted: %s " % rname, "success")
    return redirect(url_for("rulesets.index"))


@rulesets.route("/select/<string:selector>", methods=["GET"])
def select(selector):
    _rules = NaxsiRules.query.filter(NaxsiRules.ruleset == selector).order_by(NaxsiRules.sid.desc()).all()
    _selection = "Search sid: %s " % selector
    return render_template("rules/index.html", rules=_rules, selection=_selection)


def __get_rules_for_ruleset(ruleset):
    if not ruleset:
        return ''

    _rules = NaxsiRules.query.filter(
        NaxsiRules.ruleset == ruleset.name,
        NaxsiRules.active == 1
    ).all()

    nxruleset = NaxsiRuleSets.query.filter(NaxsiRuleSets.name == ruleset.name).first()
    db.session.add(nxruleset)
    db.session.commit()

    text_rules = ''.join([r.fullstr() for r in _rules])

    header = current_app.config["RULESET_HEADER"]
    header = header.replace("RULESET_DESC", ruleset.name)
    header = header.replace("RULESET_DATE", strftime("%F - %H:%M", localtime(time())))

    return header + text_rules

spike/views/sandbox.py
try:
    from urlparse import parse_qs
except ImportError:  # python3
    from urllib.parse import parse_qs

from flask import Blueprint, render_template, request, redirect, flash, url_for

from nxapi import nxlog

from spike.model.naxsi_rules import NaxsiRules
from spike.model.naxsi_whitelist import NaxsiWhitelist

sandbox = Blueprint('sandbox', __name__)


@sandbox.route("/", methods=["GET"])
def index():
    return render_template("misc/sandbox.html")


@sandbox.route("/explain_rule/", methods=["GET", "POST"])
def explain_rule():
    errors = warnings = list()
    rule_get = request.args.get('rule', '')
    rule_post = request.form.get("rule", '')
    if rule_get.isdigit():  # explain a rule by id
        _rule = NaxsiRules.query.filter(NaxsiRules.sid == rule_get).first()
        if _rule is None:
            flash('Not rule with id %s' % rule_get)
            return redirect(url_for("sandbox.index"))
    elif rule_get is not '':
        flash('Please provide a numeric id')
        return redirect(url_for("sandbox.index"))
    elif not rule_post:
        flash('Please provide a rule')
        return redirect(url_for("sandbox.index"))
    else:
        _rule = NaxsiRules()
        errors, warnings, rdict = _rule.parse_rule(rule_post)
        _rule = NaxsiRules()
        _rule.from_dict(rdict)
        _rule.errors = errors
        _rule.warnings = warnings

        if _rule.errors:
            flash('You rule is wrong', 'error')
            return render_template("misc/sandbox.html")

    if 'visualise_rule' in request.form:
        if _rule.detection.startswith('rx:'):
            return redirect('https://regexper.com/#' + _rule.detection[3:])
        else:
            flash('The rule is not a regexp, so you can not visualize it.', category='error')

    if errors:
        for error in errors:
            flash(error, category='error')
    if warnings:
        for warnings in warnings:
            flash(warnings, category='warning')

    return render_template("misc/sandbox.html", rule_explaination=_rule.explain(), rule=_rule)


@sandbox.route("/explain_whitelist/", methods=["GET", "POST"])
def explain_whitelist():
    whitelist_get = request.args.get('whitelist', '')
    whitelist_post = request.form.get('whitelist', '')
    if whitelist_get.isdigit():  # explain a whitelist by id
        _wl = NaxsiWhitelist.query.filter(NaxsiWhitelist.id == whitelist_get).first()
        if _wl is None:
            flash('Not rule with id %s' % whitelist_get)
            return redirect(url_for("sandbox.index"))
    elif whitelist_get is not '':
        flash('Please provide a numeric id')
        return redirect(url_for("sandbox.index"))
    elif not whitelist_post:
        flash('Please provide a whitelist')
        return redirect(url_for("sandbox.index"))
    else:
        _wl = NaxsiWhitelist()
        errors, warnings, rdict = _wl.parse(whitelist_post)
        _wl = NaxsiWhitelist()
        _wl.from_dict(rdict)
        _wl.errors = errors
        _wl.warnings = warnings

    if _wl.errors:
        for error in _wl.errors:
            flash(error, category='error')
            return render_template("misc/sandbox.html", whitelist=_wl)
    if _wl.warnings:
        for warnings in _wl.warnings:
            flash(warnings, category='warning')

    return render_template("misc/sandbox.html", whitelist_explaination=_wl.explain(), whitelist=_wl)


@sandbox.route('/explain_nxlog/', methods=["POST"])
def explain_nxlog():
    _nxlog = request.form.get("nxlog", '')
    if not _nxlog:
        return redirect(url_for("sandbox.index"))

    errors, nxdic = nxlog.parse_nxlog(_nxlog)
    if errors:
        flash(''.join(errors))
        return redirect(url_for("sandbox.index"))

    return render_template("misc/sandbox.html", nxlog_explaination=nxlog.explain_nxlog(nxdic), nxlog=_nxlog)

spike/templates/rules/edit.html
{% extends "misc/application.html" %}
{% block title %}Edit {{ rules_info.sid }} {% endblock %}

{% block main %}

    <h3><a href="{{ url_for('rules.view', sid=rules_info.sid) }}">{{ rules_info.msg }}</a></h3>

    <form action="{{ url_for('rules.save', sid=rules_info.sid) }}" method="POST">

    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>SID</h5>
        </div>

        <div class="col-md-6">
            <input type="hidden" name="sid" value="{{ rules_info.sid }}">
            <input type="hidden" name="active" value="{{ rules_info.active }}">
            {{ rules_info.sid }}
        </div>
    </div>

    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Active</h5>
        </div>

        <div class="col-md-6">
            {% if rules_info.active == 0 %}
                no <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                {% else %}
                yes <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            {% endif %}
        </div>
    </div>

    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Message</h5>
        </div>

        <div class="col-md-6">
            <input type="text" name="msg" placeholder="Message" value="{{ rules_info.msg }}" required size="60">
        </div>
    </div>

    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Detect</h5>
        </div>

        <div class="col-md-6">
            <input type="text" name="detection" placeholder="str|rx" value="{{ rules_info.detection }}" required size="60">
        </div>
    </div>


    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Matchzone</h5>
        </div>

        <div class="col-md-6">  <!-- FIXME This part is a fucking mess -->
            {% set dmz = [] %}
            {% for z in mz %}
                <input title="mz" type="checkbox" name="mz" value="{{ z }}"
                        {% if z in rules_info.mz.split("|") %}
                            {% if dmz.append(z) %}
                            {% endif %}
                       checked> <strong> {{ z }}</strong>
                        {% else %}
                            > {{ z }}
                        {% endif %}
                <br>
            {% endfor %}

            {% for r in rules_info.mz.split("|") %}
                {% if r not in dmz %}
                    {% if r != "custom" %}
                        <input title="mz" type="checkbox" name="mz" value="{{ r }}" checked>
                        <strong>{{ r }} </strong><br>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <input title="custom_mz" type="checkbox" name="custom_mz" value="on" {% if custom_mz %}checked{% endif %}>
            <input title="custom_mz_val" type="text" name="custom_mz_val" value="{{ custom_mz }}"
                   placeholder="Custom MZ" size="60">
        </div>
    </div>


    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Score</h5>
        </div>

        <div class="col-md-6">
            {% for s in score %}
                {% set sc,sv = rules_info.score.split(':', 1) %}
                {% if s  == sc %}
                    <input title="score_{{ s }}" type="text" name="score_{{ s }}" value="{{ sv }}" size="3">
                {% else %}
                    <input title="score_{{ s }}" type="text" name="score_{{ s }}" value="8" size="3">
                {% endif %}
                <input title="{{ s }}" type="checkbox" name="score" value="{{ s }}"
                    {% if s.value  == sc %}
                        checked> <strong> {{ s }}</strong>
                    {% else %}
                        > {{ s }}
                    {% endif %}
                <br>
            {% endfor %}
        </div>
    </div>

    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Negative</h5>
        </div>

        <div class="col-md-6">
            <input type="checkbox" id="on" name="negative" value="checked"
                    {% if rules_info.negative == 1 %} checked {% endif %} title="negative"> On
        </div>
    </div>

    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Remarks</h5>
        </div>

        <div class="col-md-6">
            <textarea cols="60" rows="10" name="rmks" title="remarks">{{ rules_info.rmks }}</textarea>
        </div>
    </div>


    <div class="row top-buffer1">
        <div class="col-md-1">
            <h5>Ruleset</h5>
        </div>

        <div class="col-md-1">
            <select name="ruleset" title="ruleset">
                {% for r in rulesets %}
                    <option value="{{ r.name }}"
                        {% if r.name  == rules_info.ruleset %}
                            selected
                        {% endif %}
                    > {{ r.name }}
                {% endfor %}
            </select>
        </div>

        <div class="col-md-1">
            <a href="{{ url_for('rulesets.index') }}" class="btn btn-info btn-xs">new ruleset</a>
        </div>
    </div>

    <div class="row top-buffer1">
        <div class="col-md-7">
            <div class="btn-toolbar" role="toolbar">
                <button type="submit" class="btn btn-success">Save Rule</button>
                <a href="{{ url_for('rulesets.select', selector=rules_info.ruleset) }}" class="btn btn-primary">View Ruleset</a>

                {% if rules_info.active == 0 %}
                    <a href="{{ url_for('rules.deact', sid=rules_info.sid) }}" class="btn btn-success">Activate Rule</a>
                {% else %}
                    <a href="{{ url_for('rules.deact', sid=rules_info.sid) }}" class="btn btn-warning">Deactivate Rule</a>
                {% endif %}

                <a href="{{ url_for('rules.del_sid', sid=rules_info.sid) }}" class="btn btn-danger">Delete Rule</a>
            </div>
        </div>
    </div>
</form>

{% endblock %}

spike/templates/rules/import.html
{% extends "misc/application.html" %}
{% block title %}Import Naxsi-Rule{% endblock %}


{% block main %}

    <h2>Import Rules From File</h2>

    <form action="{{ url_for('rules.import_rules') }}" enctype="multipart/form-data" method="POST">
        <div class="form-group">
            <div class="row">
                <div class="col-md-1">
                    <select title="ruleset" name="ruleset">
                        {% for r in rulesets %}
                            <option value="{{ r.name }}"> {{ r.name }}
                        {% endfor %}
                    </select>
                </div>

                <div class="col-md-1">
                    <a href="{{ url_for('rulesets.index') }}" class="btn btn-info btn-xs">new ruleset</a>
                </div>
            </div>
        </div>

        <div class="form-group">
	            <input name="file" type="file" required>

            <div class="row top-buffer1">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-success">Import Rule(s)</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

spike/templates/rules/index.html
{% extends "misc/application.html" %}
{% block title %}SPIKE! - WAF Rules Builder{% endblock %}

{% block main %}

    <h2>Naxsi - Rules ( {{ rules | length }} )</h2>
    <p><strong>{{ selection }}</strong></p>

    <hr>

    {% for rule in rules %}
        <div class="row top-buffer1">
            <div class="col-md-2">
                <h5>{{ rule.msg }}</h5>
            </div>

            <div class="col-md-3">
                <h5>{{ rule.detection }}</h5>
            </div>

            <div class="col-md-7">
                <div class="btn-toolbar" role="toolbar">
                    <a href="{{ url_for('rules.edit', sid=rule.sid) }}" class="btn btn-info" title="Edit Rule">Edit</a>
                    <a href="{{ url_for('rules.view', sid=rule.sid) }}" class="btn btn-default" title="View Rule">View</a>
                    <a href="{{ url_for('rules.test', sid=rule.sid) }}" class="btn btn-default" title="Test Rule">Test</a>
                    <a href="{{ url_for('sandbox.explain_rule', rule=rule.sid) }}" class="btn btn-default" title="View Rule">Explain</a>
                    <a href="{{ url_for('rules.plain', sid=rule.sid ) }}" class="btn btn-default" title="Plain Rule">Plain</a>
                    <a href="{{ url_for('rules.del_sid', sid=rule.sid) }}" class="btn btn-danger" title="View Rule">Delete</a>
                </div>
                <b>{{ rule.ruleset }}</b>
            </div>
        </div>
    {% endfor %}

{% endblock main %}

spike/templates/rules/new.html
{% extends "misc/application.html" %}
{% block title %}Create Naxsi-Rule{% endblock %}


{% block main %}

    <h2>New Rule</h2>

    <form action="{{ url_for('rules.new') }}" method="POST">

        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>SID</h5>
            </div>

            <div class="col-md-6">
                {{ latestn }}
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Message</h5>
            </div>

            <div class="col-md-6">
                <input type="text" name="msg" size="60" placeholder="Message" required>
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Detect</h5>
            </div>

            <div class="col-md-6">
                <input type="text" name="detection" size="60" placeholder="str|rx" required>
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Matchzone</h5>
            </div>

            <div class="col-md-6">
                {% for z in mz %}
                    <input title="matchzone" type="checkbox" name="mz" value="{{ z }}"> {{ z }} <br>
                {% endfor %}
                <input title="custom_mz" type="checkbox" name="custom_mz" value="on">
                <input title="custom_mz_val" type="text" name="custom_mz_val" placeholder="Custom MZ">
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Negative</h5>
            </div>

            <div class="col-md-6">
                <input title="negative" type="checkbox" name="negative" value="checked">
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Score</h5>
            </div>

            <div class="col-md-6">
               {% for s in score %}
                    <input title="score_{{ s }}" type="text" name="score_{{ s }}" value="8" size="3">
                    <input title="{{ s }}" type="checkbox" name="score" value="{{ s }}"> {{ s }}
                    <br>
                {% endfor %}
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Remarks</h5>
            </div>

            <div class="col-md-6">
                <textarea cols="60" rows="10" name="rmks" title="remarks"></textarea>
            </div>
        </div>


        <div class="row top-buffer1">
            <div class="col-md-1">
                <h5>Ruleset</h5>
            </div>

            <div class="col-md-1">
                    <select title="ruleset" name="ruleset">
                        {% for r in rulesets %}
                            <option value="{{ r.name }}"> {{ r.name }}
                        {% endfor %}
                    </select>
            </div>

            <div class="col-md-1">
                <a href="{{ url_for('rulesets.index') }}" class="btn btn-info btn-xs">new ruleset</a>
            </div>
        </div>

    
        <div class="row top-buffer1">
            <div class="col-md-6">
                <button type="submit" class="btn btn-success btn-lg">Save Rule</button>
            </div>
        </div>
    </form>
{% endblock %}

spike/templates/rules/view.html
{% extends "misc/application.html" %}
{% block title %}View {{ rule.sid }} {% endblock %}


{% block main %}

    <h3>
        <a href="{{ url_for('rules.edit', sid=rule.sid) }}">{{ rule.sid }} - {{ rule.msg }}</a>
        <a href="{{ url_for('rules.edit', sid=rule.sid) }}" class="btn btn-lg btn-primary">Edit Rule</a>
    </h3>

    <pre>
  
{{ rtext }}

    </pre>


{% endblock %}